### ISSUE TITLE
Tensorflow on Android[status-in progress]

### ISSUE THREAD

**Issue by tylermzeller** [jihunhamm/Crowd-ML#11]
Currently [only inference is supported](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android) from Tensorflow on Android devices. The [Android demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) uses the very basic [Tensorflow Java API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md) which does not support training (only the python API supports sophisticated training). However, [this C++ example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/tutorials/example_trainer.cc) shows that training in languages other than python is not impossible. I think using [this reference for manual backpropagation](http://blog.aloni.org/posts/backprop-with-tensorflow/) will be useful in the future.

Edit March 10, '17:
After some continued research by me and David Soller (@3ygun) we have found a great resource about [training models in C++](https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API). The great part about this article is that it has convinced me that training is possible simply from the [Tensorflow Java API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md) with slight modification (see link above). The models will need to be pre-generated from python code, and then loaded onto the device (or downloaded from the server). The only requirement is that there should be a named operation for training in the model.

Line 14 in [training models in C++](https://tebesu.github.io/posts/Training-a-TensorFlow-graph-in-C++-API) shows this named operation:

```
optimizer = tf.train.AdamOptimizer().minimize(cost, name="train")
```

He runs this operation on line 41 in the C++ code block:

```
TF_CHECK_OK(session->Run({{"x", x}, {"y", y}}, {}, {"train"}, nullptr)); // Train
```

I believe the above line can be achieved purely from the Java API, so I'm changing the status to 'plausible'.

**Comment by 3ygun** [comment]
@tylermzeller and I are tracking any separate progress/examples **not** related to crowd ml we need to sync on [this repo](https://github.com/chelexa/tensorflow-on-android)

**Comment by tylermzeller** [comment]
Tensorflow is now integrated with Android Studio and we are ready to begin tests on training in Android.

**Comment by tylermzeller** [comment]
Success! Was able to train the model for ten iterations using the adam optimizer! Here are the associated costs of each iteration: 
![training](https://cloud.githubusercontent.com/assets/14643641/24591901/5e53c012-17da-11e7-80c8-808b63f9eae2.jpg)

**Comment by tylermzeller** [comment]
Watch [this video](https://www.youtube.com/watch?v=3dqqSdQ7fD8) for a demo of the app running 10,000 iterations of training

**Comment by 3ygun** [comment]
[https://github.com/chelexa/tensorflow-on-android]() has our final work from the class project on this.

Overall found:

- [x] Can use the [TensorFlow Java](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/package-summary) library as used in the [TensorFlow Android Example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android)
- [x] Have user construct the model in Python and export to a `.pb` file which will then be loaded into the system.
   - Enables easy model development and should give us an easy way to distribute models to compute devices

Closing as the initial theory work is complete moving issue tracking to #23
