### ISSUE TITLE
Continued Server Cleanup

### ISSUE THREAD

**Issue by 3ygun** [jihunhamm/Crowd-ML#20]
# Goals

Continued server building on #19 

# Parts

- [ ] Need to do some further testing to affirm I didn't break anything
- [x] Extract Firebase config to allow ENV's instead of committing credential information #21 
- [ ] Remove duplicate loading of configuration in tests
- [x] Remove old configuration files `Constants.js` #21

**Comment by tylermzeller** [comment]
Node version must be > 6. Otherwise, I'm going to close this.
