### ISSUE TITLE
Possible memory leak when service is running

### ISSUE THREAD

**Issue by tylermzeller** [jihunhamm/Crowd-ML#24]
Steps to reproduce:

- Open up client, and make sure service is running

- Make sure server is not running. If it is, close it down to ensure no processing on the client is happening. 

- Open the Android monitor and select the crowd-ml:datasend process. View the allocated memory continuously increasing in the performance profiler. 

This may be due to the wifi listener, because that is the only running thread in the :datasend process.

**Comment by 3ygun** [comment]
Is this in the `tensorflow` branch?

**Comment by tylermzeller** [comment]
No, I can view it on master.

**Comment by 3ygun** [comment]
Was able to reproduce.
